#!/bin/bash

echo '<metalink xmlns="urn:ietf:params:xml:ns:metalink">'
jq --slurp -r '
	map({	url: .url[0]|split("|")[0],
			size,
			instance_id,
			checksum: .checksum|first,
			checksum_type: .checksum_type|first,
			replica}) |
	group_by(.instance_id|sub("\\.nc_[0-9]+";".nc")|gsub("\\.(?!nc$)";"/")) |
	map(reduce .[] as $i ({urls: []}; {urls: [.urls[],$i.url]} + $i)) |
	map(	"\t<file name=\""+(.instance_id|sub("\\.nc_[0-9]+";".nc")|gsub("\\.(?!nc$)";"/"))+"\">",
			"\t\t<size>"+(.size|tostring)+"</size>",
			"\t\t<hash type=\""+(.checksum_type|tostring)+"\">"+(.checksum|tostring)+"</hash>",
			(.urls|unique|map("\t\t<url priority=\"1\">"+(.)+"</url>"))[],
		"\t</file>\n")[]'
echo '</metalink>'
