#!/bin/bash

usage() {
    echo "esgf-check [ -h ] [ -m ] [ -r ROOT ] FILES..." >&2
}

check_file() {
    if [ ! -f "$1" ]; then
        echo ERROR missing $1
    elif [ ! -s "$1" ]; then
        echo ERROR size0 $1
    elif [ -f "${1}.aria2" ]; then
        echo ERROR aria2 ${1}.aria2
    fi
}

while [[ $# -gt 0 ]]
do
    case "$1" in
    -h | --help)
        usage
        exit 1
        ;;
    -m | --metalink)
        metalink="true"
        shift
        ;;
    -r | --root)
        root="${2%/}"
        shift 2
        ;;
    -*)
        echo "Error: Unknown options: $1" >&2
        exit 1
        ;;
    *)
        files="$@"
        break
        ;;
    esac
done

if [ -z "$root" ] && [ ! -z "$metalink" ]; then
    root=/oceano/gmeteo/DATA/ESGF/REPLICA/DATA
fi

# Input files are metalink files
if [ ! -z "$metalink" ] && [ ! -z "$files" ]; then
    for dataset in $(awk -F'"' '/<file name/{print $2}' $files)
    do
        fpath=${root}/${dataset}
        check_file $fpath
    done
    exit 0
fi

# Input files are regular files (one path per line)
if [ ! -z "$files" ]; then
    for dataset in $(cat $files)
    do
        fpath=${dataset}
        check_file $fpath 
    done
    exit 0
fi

# Read from stdin (one path per line)
if [ ! -z "$files" ]; then
    for dataset in $(cat -)
    do
        fpath=${dataset}
        check_file $fpath 
    done
    exit 0
fi
