#!/bin/bash

awk '
BEGIN {
  FS=",";ORS="";started=0
}
NF<8{ next }
NR>2 && started { print "" }
NR>1{
  started=1
  dataset=$1

  gsub(/"/, "", dataset)
  nfacets=split(dataset,facets,".")
  project=facets[1]
  activity_id=facets[2]
  institution_id=facets[3]
  source_id=facets[4]
  experiment_id=facets[5]
  variant_label=facets[6]
  grid_label=facets[7]

  nvariables=split("pr,psl,sftlf,tas,tasmax,tasmin",variables,",")
  for(i=3;i<=(nvariables+3);i++) {
    if($i == "true") {
      variable_id=variables[i-2]

      if(variable_id=="sftlf") {
        frequency="fx"
      } else {
        frequency="day"
      }

      printf "%s.%s.%s.%s.%s.%s.%s.%s.%s\n", project, activity_id, institution_id, source_id, experiment_id, variant_label, frequency, variable_id, grid_label
    }
  }
}' CMIP6_day_1run.csv > master_ids_to_download

# groupby by dataset_id to greatly reduce number of comparisions
# since it's very time consuming
jq --slurp --rawfile master_ids master_ids_to_download '
	($master_ids|split("\n")[0:-1]) as $master_ids_list |
	map(. + {dataset_id: (.master_id|split(".")[:9]|join("."))}) |
	group_by(.dataset_id) |
	map({dataset_id: .[0].dataset_id, datasets: .}) |
	map(select(.dataset_id == $master_ids_list[])) |
	.[].datasets[]' CMIP6.json | ../esgf-metalink > metalink
