name: binder-atlas-climate4r-v2.5.4
channels:
  - conda-forge
  - nodefaults # only conda-forge dependencies
  - conda-forge/label/broken # just in case some dependencies become "broken"
dependencies:
  # explicit dependency on R and Python versions
  - r-base ==3.6.3
  - python ==3.7.12
  # climate4R v2.5.4 dependencies
  - r-climate4r.udg ==0.2.3
  - r-loader.java ==1.1.1
  - r-loader ==1.7.1
  - r-loader.ecoms ==1.4.6
  - r-transformer ==2.1.3
  - r-downscaler ==3.3.3
  - r-downscaler.keras ==1.0.0
  - r-visualizer ==1.6.1
  - r-convertr ==0.2.0
  - r-geoprocessor ==0.2.0
  - r-climate4r.climdex ==0.2.2
  - r-climate4r.indices ==0.2.0
  - r-loader.2nc ==0.1.2
  - r-firedanger ==1.1.0
  - r-value ==2.2.2
  - r-climate4r.value ==0.0.2
  - r-mopa ==1.0.0
  - r-drought4r ==0.2.0
  - r-climate4r.datasets ==0.0.1
  - iris

  # Jupyter and JupyterHub dependencies
  - r-irkernel
  - jupyter #==1.0.0
  - jupyterhub #==1.4.2
  - notebook #==6.4.2
  - jupyterlab #==3.1.4
  - jupyter_nbextensions_configurator
  - jupyterlab-git
  - jupyterlab-github
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor

  # required for decouple binder and repo
  - nbgitpuller
  # required for jupyter books
  - jupyter-book
  - jupytext >=0.16
  # R extra dependencies used by notebooks and/or scripts
  - r-devtools
  - r-gridextra
  - r-xtable
  - r-magrittr
  - r-httr
  - r-lattice
  - r-latticeextra
  # Python extra dependencies used by notebooks and/or scripts
  - xarray
  - regionmask
  # Other extra dependencies used by notebooks and/or scripts
  - cdo
  - nco
  # explici PIP dependency
  - pip
